export const util = () => {}

// date: 'Дата'
// document: 'Документ'
// debitAccount: 'Счет Дт'
// debitSubaccount1: 'Субконто1 Дт'
// debitSubaccount2: 'Субконто2 Дт'
// debitSubaccount3: 'Субконто3 Дт'
// creditAccount: 'Счет Кт'
// creditSubaccount1: 'Субконто1 Кт'
// creditSubaccount2: 'Субконто2 Кт'
// creditSubaccount3: 'Субконто3 Кт'
// amount: 'Сумма'
// description: 'Содержание'

// documentNumber: 'Номер
// date: 'Дата'
// amount: 'Сумма'
// payerAccount: 'ПлательщикСчет'
// payerName: 'Плательщик'
// payerINN: 'ПлательщикИНН'
// payerKPP: 'ПлательщикКПП'
// payerCheckingAccount: 'ПлательщикРасчСчет'
// recipientAccount: 'ПолучательСчет'
// recipientName: 'Получатель'
// recipientINN: 'ПолучательИНН'
// recipientCheckingAccount: 'ПолучательРасчСчет'
// budgetClassificationCode: 'ПоказательКБК'
// paymentPriority: 'Очередность'
// paymentPurpose: 'НазначениеПлатежа'
